sudo: false
language: scala
scala:
  - 2.12.3
jdk:
  - oraclejdk8
node_js:
  - "stable"
before_script:
  - npm install jsdom
script:
  - sbt clean +test
  - sbt coverage coreJVM/test communicationJVM/test server/test serverUndertow/test stream/test appJVM/test
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete