sudo: false
language: scala
scala:
  - 2.12.0
jdk:
  - oraclejdk8
language: node_js
node_js:
  - "6.1"
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete