sudo: false
language: scala
scala:
  - 2.12.1
jdk:
  - oraclejdk8
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom
  - npm install canvas
script:
  - sbt clean +test
  - sbt coverage coreJVM/test communicationJVM/test server/test serverUndertow/test stream/test appJVM/test
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete